# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 630)
        MainWindow.setStyleSheet("background-color: #22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("BackGround-color:#22222e\n")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 221))
        self.frame.setStyleSheet("background-color: #fb5b5d\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 441, 101))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(72)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 241, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.input_url = QtWidgets.QLineEdit(self.centralwidget)
        self.input_url.setGeometry(QtCore.QRect(10, 250, 321, 20))
        self.input_url.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 5;\n"
"color: white;")
        self.input_url.setText("")
        self.input_url.setObjectName("input_url")
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setGeometry(QtCore.QRect(350, 250, 75, 23))
        self.check_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5d5d;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244\n"
"}")
        self.check_btn.setObjectName("check_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        self.video_title = QtWidgets.QLineEdit(self.centralwidget)
        self.video_title.setGeometry(QtCore.QRect(10, 320, 431, 20))
        self.video_title.setStyleSheet("background-color: #22222e;    \n"
"border: 2px solid #f66867;\n"
"border-radius: 5;\n"
"color: white;")
        self.video_title.setObjectName("video_title")
        self.video_capture = QtWidgets.QLabel(self.centralwidget)
        self.video_capture.setGeometry(QtCore.QRect(50, 360, 351, 181))
        self.video_capture.setStyleSheet("background-color: white;\n"
"border-radius: 5;")
        self.video_capture.setText("")
        self.video_capture.setObjectName("video_capture")
        self.input_folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_folder_btn.setGeometry(QtCore.QRect(360, 560, 75, 23))
        self.input_folder_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5d5d;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244\n"
"}")
        self.input_folder_btn.setObjectName("input_folder_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 560, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white")
        self.label_6.setObjectName("label_6")
        self.input_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.input_folder.setGeometry(QtCore.QRect(100, 560, 251, 20))
        self.input_folder.setStyleSheet("background-color: #22222e;    \n"
"border: 2px solid #f66867;\n"
"border-radius: 5;\n"
"color: white;")
        self.input_folder.setObjectName("input_folder")
        self.save_in_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_in_Btn.setGeometry(QtCore.QRect(10, 590, 75, 23))
        self.save_in_Btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5d5d;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fa4244\n"
"}")
        self.save_in_Btn.setObjectName("save_in_Btn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 590, 331, 23))
        self.progressBar.setStyleSheet("color: white;")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Скачивалка"))
        self.label_3.setText(_translate("MainWindow", "Ссылка на видео"))
        self.check_btn.setText(_translate("MainWindow", "Проверить"))
        self.label_4.setText(_translate("MainWindow", "Информация"))
        self.input_folder_btn.setText(_translate("MainWindow", "Выбрать"))
        self.label_6.setText(_translate("MainWindow", "Сохранить в"))
        self.save_in_Btn.setText(_translate("MainWindow", "Скачать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
